### ISSUE TITLE
Pub example tab link results in 404

### ISSUE THREAD

**Issue by shihaohong** [tekartik/sembast.dart#100]
In pub, the [Example tab](https://pub.dev/packages/sembast#-example-tab-) link to example/main.dart results in a 404 error. 

I think that instead of https://github.com/tekartik/sembast.dart/blob/master/example/main.dart, it should link to https://github.com/tekartik/sembast.dart/blob/master/sembast/example/main.dart

**Comment by alextekartik** [comment]
Thanks for the report. That seems to be an issue for the pub site. Other package (provider) has the same issue, the link is generated by their server

**Comment by shihaohong** [comment]
How does pub determine the link? Would it be more appropriate to file a bug elsewhere?

**Comment by alextekartik** [comment]
I don't know, maybe in https://github.com/dart-lang/pub-dev

**Comment by isoos** [comment]
pub.dev uses the `homepage` (or if present the `repository`) property in `pubspec.yaml`, and if it is a recognisable GitHub or GitLab URL, it uses the relative example path from the uploaded package archive (`example/main.dart`) to construct the final link.

This repository is non-standard, because it uses a subdirectory: `semblast`. pub.dev has no prior knowledge of this, and cannot figure it out on its own. There are similar repositories, usually they contain multiple packages in sub-directories, and they use a "deep" URLs as their `homepage`, e.g.:
https://github.com/tekartik/sembast.dart/tree/master/sembast

If you use such URL, the example link will be pointing to the right place. I'm also curious why you have structured the project this way, could you please fill in the details on https://github.com/dart-lang/pub-dev/issues/3092 (I'd like to transfer the pub-related discussion to that site)

**Comment by alextekartik** [comment]
Thanks for the info. I will fix the homepage.

**Comment by alextekartik** [comment]
Fixed in 2.1.2+2
