### ISSUE TITLE
Mac os support

### ISSUE THREAD

**Issue by vvalladolidIV** [tekartik/sembast.dart#124]
This lib works with macos desktop?

**Comment by alextekartik** [comment]
yes both Flutter and VM

**Comment by salime45** [comment]
There are some example ?

**Comment by alextekartik** [comment]
There is a bare minimum example here: https://github.com/alextekartik/flutter_app_example/tree/master/demosembast

that works on all platforms (ios, android, mac, web - event linux and windows with some additionnal setup).

Since it is a pain to maintain projects for all target, only the minimum needed files are checked in. You should be able to re-create the needed project files (gradle, workspace) using flutter create . in each application folder.

```
cd demosembast
flutter create .
flutter run -d macos
```
