### ISSUE TITLE
Encrypting the database file

### ISSUE THREAD

**Issue by jagan999** [tekartik/sembast.dart#13]
Is there a way to encrypt the database? I have a requirement of a secure database

**Comment by alextekartik** [comment]
Not at the moment but that could easily be implemented by encrypting each record when saved to disk. It might have a performance impact at start time.

I will look into it, likely not before a week or 2. One solution I see would be to provide a way to decrypt/encrypt a record using a user function so that any algorithm could be provided

**Comment by alextekartik** [comment]
I added a way to support encryption and an example of an encrypted database in 1.13.3 published on pub.
More information here: https://github.com/tekartik/sembast.dart/blob/master/doc/codec.md

**Comment by jagan999** [comment]
Thanks.

**Comment by zubairehman** [comment]
The above link doesn't work, could you please add a sample code in an example project or provide a code snippet here encrypt a database. Thanks

**Comment by alextekartik** [comment]
Sorry. I updated the link <https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/codec.md> which contains a snippet. You can look at the unit test here as well: https://github.com/tekartik/sembast.dart/blob/ea5ac4d401b96651a8aad66e2fe86ff743d60eb5/sembast/test/compat/doc_test.dart#L113-L119

**Comment by zubairehman** [comment]
Thanks, got that
