### ISSUE TITLE
Is it safe to apply encryption to Sembast db in production?

### ISSUE THREAD

**Issue by andriy-gulak-ew** [tekartik/sembast.dart#141]
I have a prepopulated sembast db in the production app. Now I'm planning to use encryption as you described in https://pub.dev/packages/sembast#codec-and-encryption

Is it safe to use the following code on existing db:
```dart
var codec = getEncryptSembastCodec(password: '[your_user_password]');
// Open the database with the codec
Database db = await factory.openDatabase(dbPath, codec: codec);
``` 

Can you please share your thoughts about encryption an existing sebmast db? Is there a safe/right way to encrypt data in such kind of db?

**Comment by alextekartik** [comment]
Hi. I see two topics in your issue

1. How to migrate an existing database to an encrypted database
2. How safe is it to apply encryption in production

### 1. How to migrate an existing database to an encrypted database

On the first topic, no you cannot open an existing non-encrypted database with an encryption codec. A database codec has to be specify at creation time. One solution is to export the existing database and import it in a new encrypted database. There are [utilities](https://pub.dev/documentation/sembast/latest/sembast.utils.sembast_import_export/sembast.utils.sembast_import_export-library.html) for that. As a side note, the `importDatabase` has new codec parameter as of 2.4.1 (that was missing up to now, thanks for raising your issue!)

Below is a simple example converting a non-encrypted database to an encrypted one.

```dart
// Open my existing database and close it
db = await factory.openDatabase('my_existing.db');
var exportMap = await exportDatabase(db);
await db.close();

// Import the existing export in a newly created database using encryption
db = await importDatabase(exportMap, factory, 'my_encrypted.db',
    codec: codec);

// The new database is now encrypted, you can deleted the old one
```

(This will be added to the documentation).

### 2. How safe is it to apply encryption in production

Not easy to answer on this one. I know some people are using the encrypted codec provided as a sample as is (it was refined since the beginning, see https://github.com/tekartik/sembast.dart/issues/35). It will definitely slow down initial load time.

Regarding robustness, an encrypted is not less/more robust than a non-encrypted one. So far I never got any complaint about data-loss. `sembast_sqflite` is a solution to use sqflite backend (instead of plain text file) which is cross process safe and known for its robustness.

**Comment by andriy-gulak-ew** [comment]
Thank you for the great explanation! Really helpful.
