### ISSUE TITLE
Search Ranking 

### ISSUE THREAD

**Issue by tobinharris** [tekartik/sembast.dart#153]
Hi,

Can you think of any way to search ranking, so that certain results are scored higher and return to the top?

For example, an exact match on name would score higher than a partial match.

I was thinking about how custom filters return a `bool` if there is a match. It would be quite cool if they returned an `int` representing a rank. This way, you could implement some kind of scoring depending on how good a match is, and then order by rank.

T

**Comment by alextekartik** [comment]
Interesting. Hard to make something generic for a specific need (basically a virtual sort order on a transient property) so I don't know yet how to plug that without some breaking changes. Since I don't have a good solution for this now, what could be done using custom filters would be storing the ranking in a map during the custom filter when returning true (key being the record key, value being the score) and sort the results based on this score.

Example:

```dart
// We assuming here a key is an String.
// We define the score as int.
var rankings = <String, int>{};

var filter = Filter.custom((record) {
  // ...
  // return false if the record does not match
  // ...

  // It matches let's give a score (int) - to implement
  var score = getRecordScore(record);
  rankings[record.key as String] = score;

  return true;
});
var results = await store.find(db, finder: Finder(filter: filter));

// sort the results by reverse ranking (i.e. highest score first)
results.sort((snapshot1, snapshot2) {
  // compare the score of both records.
  return rankings[snapshot2.key] - rankings[snapshot1.key];
});
```

**Comment by tobinharris** [comment]
Thanks! That literally sorts it for now :)

It's working for 200 records, we'll see what happens when we get to thousands.
