### ISSUE TITLE
benchmarks

### ISSUE THREAD

**Issue by chimon2000** [tekartik/sembast.dart#159]
I recently added Sembast to a fork of the hive benchmark, and I wanted to make sure that I have implemented it correctly.  You can view the change comparison here:

https://github.com/hivedb/hive_benchmark/compare/master...chimon2000:feat/sembast

**Comment by alextekartik** [comment]
Thanks. I proposed some fix in a pull request that you can take a look. The following code is not correct:

```dart
await _db.transaction((txn) async {
  entries.forEach((key, val) async {
    await store.record(key).put(_db, val);
  });
});
```

First don't use for each with async function in a transaction. You must await properly the actions in a transaction. Also the `txn` object must be used as the database client in a transaction instead of `_db`. This leads to the following correction:

```dart
await _db.transaction((txn) async {
  for (var entry in entries.entries) {
    await store.record(entry.key).put(txn, entry.value);
  }
});
```

**Comment by chimon2000** [comment]
I knew there was some reason for the high numbers in the benchmark. Thanks!

**Comment by stefandevo** [comment]
@chimon2000 any results available? Looking for the fastest nosql db for flutter
