### ISSUE TITLE
Slow Open database

### ISSUE THREAD

**Issue by rafaelcorbellini-egsys** [tekartik/sembast.dart#167]
A database with only one Store with one  large record (string with  lenght = 3413440) are taken around 23614 ms to execute `databaseFactoryIo.openDatabase`

is that right? are some way to avoid that?

**Comment by alextekartik** [comment]
While there is no limitation, even database like firestore and sqlite has 1MB limitation so you better try to fit in this situation. 23s looks very slow though. just decoding a 3Mb json could be slow. Sembast also ran through the data which could maybe be improved. Do you have some sample data you could share (export or database file itself).

You might also compare storing a json string vs storing a decoded (map/list) version

**Comment by rafaelcorbellini-egsys** [comment]
I already had a value key store (string/string), I decided to keep and use sembast, so I always have a key and a value, and the value in question is a string (from a json list), but I decode it myself , and I don't understand why it takes so long to open the database, I even requested some registration.

**Comment by flutter-painter** [comment]
Hi,
This is related to https://github.com/tekartik/sembast.dart/issues/241
I encounter everlasting db loading on startup due to far far far too many objects in collections.
This being said, if the database is first opened empty, and if the app fetches and adds objects in a second phase,
Then app can handle huge collection with low latency ; hot reload will work, hot restart will bloat for hours.

I understand that SEMBAST loads everything into memory at init,
I also see that it is able to process huge list of objects once opened,
So wouldn't there be a way to trick it for a lazy/blind opening and then load ?

**Comment by alextekartik** [comment]
That is unfortunately a design flaw. sembast is not made for huge database. Even if we delay the opening, the same issue (loading everything in memory) will happen at some point.
What you could try to speed up initial loading (but UI will be blocked so best to do during a splash screen before calling runApp on flutter)

```
disableSembastCooperator();
/// Open you database
...

/// Once opened re-enabled
enableSembastCooperator();
```

In theory you should not get much gain. If you see a huge difference, good if you could share your database (along with some technical info sembast/sembast_web/sembast_sqflite, mac/linux/windows/andorid/ios) so I can take a closer look. Otherwise my recommendation would be to try another database (hive, objectbox, sqflite).

**Comment by flutter-painter** [comment]
Thanks so much for your answer, this is a jailbreak ! 
Database opened in around 2 minutes, and app launch even with + 500k objects \°/
This also unlocks hot reload, though it takes around 6 minutes.
As mentionned, I was no longer able to open app before, so this is a huge gain.
DB is sembast, used on desktop (windows and mac), 550MB.

Will stick with SEMBAST, which has many assets such as encrypted data, 

This is another topic but...
Sqflite implies switching from NoSQL to SQL which is not on the agenda, 
I don't know about using Hive, breaking changes and possible data loss in 2.0 is anything but reassuring, 
ObjectBox is not free to use, or not meant to be passed a certain volume, it also requires generating stuff which is a pain.

Walking on unknown territory here...
But what if there was a way to split it ?
Either split collections across several sembast files,
AND/OR split db loading across isolates.

**Comment by alextekartik** [comment]
> and app launch even with + 500k objects \°/

I never thought sembast was able to handle that...

Some optimizations:
- If you don't need cross store transactions, you could split your database in multiple databases (with 1 or more store per database).
- Encryption slow down read/write a lot. If you split the database, you would consider to only encrypt the database that needs it or don't use encryption at all and encrypt fields you want manually.

**Comment by flutter-painter** [comment]
@alextekartik I tried to split in multiple databases but face issue when inheriting the same object Database in Provider.
At run time I get Type Cast Error.
A simple extension such as below does not work and leads me to re-implement most of sembast since there is no single `SembastDatabase newDatabase(DatabaseOpenHelper openHelper);`
Am I missing something obvious ?
```dart

class DbTickets extends SembastDatabase {
  DbTickets(DatabaseOpenHelper openHelper) : super(openHelper);
}

abstract class DbProducts extends sembast.Database {}
```

**Comment by flutter-painter** [comment]
Only way I found is to wrap them like this, a lot of code rewrite, but still **it works** :D 


```dart
abstract class Wrapper {
  Database db;
}

class DbTheSecond extends Wrapper {
  final Database db;
  DbTheSecond(this.db);
}
```

**Comment by alextekartik** [comment]
@flutter-painter SembastDatabase is not meant to be subclassed. Prefer composition as you did in your Wrapper.

**Comment by flutter-painter** [comment]
Hi @alextekartik,
Following-up on this topic.
Could you consider exposing this wrapper inside Sembast package ?
This would make it easier to use dbs accross projects.
The use case here is adding persistence to [aptabase](https://github.com/flutter-painter/aptabase_flutter) to store events and send them once back online.
The idea is that Aptabase only exposes the eventsservices, not the database, which is passed by the client.
This avoids duplicating the db tasks and lets devs set-up this service within their own state-management.
Having a common wrapper class would allow devs to use a dedicated db.
I can submit a PR if you prefer..









```dart
abstract class Wrapper {
  final Database db;
  Wrapper(this.db);
}
```
