### ISSUE TITLE
Documentation: How do I update a record?

### ISSUE THREAD

**Issue by DavidMihola** [tekartik/sembast.dart#2]
I hope this is the correct place to ask my question - if I should rather post it on stackoverflow, please tell me and I will do so!

I am currently playing around with Sembast in Flutter and I am trying to use it to store bookmarks in a Manga reader app.

I am writing bookmarks like this:

    var newRecord = new Record(bookmarkStore, {
      'mangaId': bookmark.mangaId,
      'chapterId': bookmark.chapterId,
      'page': bookmark.page,
    });

    await db.inTransaction(() async {
      await db.putRecord(newRecord);
    });

But I haven't found any way to update a record (I only want to store the latest bookmark for each `mangaId` - I tried first deleting the old record like this:

    Record record = await bookmarkStore.findRecord(new Finder()
        ..filter = new Filter.equal("mangaId", bookmark.mangaId));

    if (record != null) {
      debugPrint('deleting old bookmark');
      await db.delete(record.key);
    }

But somehow the old record still remains in the database...

**Comment by alextekartik** [comment]
Definitely the proper place to ask questions. Thanks. I realized while using it that the Record API is not that great since sometimes it requires a store parameter and sometimes not...By default it uses the default store so in your example you are not deleting the record.key from the proper store (the key does not tell which store is used). To update a record simply modify a record you created, get or find and call putRecord again. To delete a record in a specific store, use the API in the store itself (confusing...)
````
var record = new Record(bookmarkStore, {
  'mangaId': bookmark.mangaId,
  'chapterId': bookmark.chapterId,
  'page': bookmark.page,
});

// create record (only the returned object has the key set)
record = await db.putRecord(record);

// get the record (use the store API)
bookmarkStore.getRecord(record.key);

// update it
record.value['page'] = 4;
record = await db.putRecord(record);

// delete it
// warning here it must be deleted in the proper store...
bookmarkStore.delete(record.key);
````

I'm not that happy with the Record API. I tried to made it really convenient when a single store is used, but I realize it makes it ackward to have the store info in the record and sometimes allow using the record api of the database (put) and sometimes require using the records api of the store (get, delete, find). Suggestions welcome...

**Comment by DavidMihola** [comment]
Oh, that's embarrassing: I didn't think to try `record.value['page'] = 4` -  I just tried `record['page'] = 4` which, of course, didn't work...

Thank you very much for the detailed explanation!

**Comment by alextekartik** [comment]
And I will definitely add support for record['page'] = 4 !

**Comment by alextekartik** [comment]
Done in sembast 1.3.6 published today. Indeed we were able to read a property but not set it this way...

**Comment by joardar-aditya** [comment]
Is there any way we can use a map to change multiple fields?

**Comment by alextekartik** [comment]
Yes, you just need to put multiple fields in the map.

Example to delete the field `color` and update the sub field `address.city`:
```dart
var record = store.record(key);
 // Updating some fields
await record.update(db,
  {'color': FieldValue.delete, 'address.city': 'San Francisco'});
```

See https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/writes.md#updating-fields

**Comment by joardar-aditya** [comment]
Got it! Thanx @alextekartik

**Comment by pierre-gancel** [comment]
My 2 cents, using a filter yields better result : 
```dart
final _dbStore = sembast.intMapStoreFactory.store('my_cool_list');
await _dbStore.update(_database, object.toJson(),
        finder: sembast.Finder(filter: sembast.Filter.equals('id', object.id)));
```
