### ISSUE TITLE
StoreRef have no more add method and anothers one

### ISSUE THREAD

**Issue by TercyoStorck** [tekartik/sembast.dart#200]
Hi,

I would like to know why `StoreRef` have no more add and more others. I use to do something like this `StoreRef get store => intMapStoreFactory.store(storeName)` but now I can't =/

So. How can I do the same thing that I used to do?

**Comment by alextekartik** [comment]
Hi. Well you should still be able to write

```dart
StoreRef<int, Map<String, dynamic>> get store => intMapStoreFactory.store(storeName)
```

and

```dart
await store.add(db, map);
```

without changing your imports. However add/put is now available as an [extension](https://pub.dev/documentation/sembast/latest/sembast/SembastStoreRefExtension.html). Autocomplete is not fully working yet for extensions. This also means that your min sdk should be '>=2.6.0' in your pubspec.yaml. Can you check that? Otherwise can you report the error you are seeing? thanks!

**Comment by TercyoStorck** [comment]
> Hi. Well you should still be able to write
> 
> ```dart
> StoreRef<int, Map<String, dynamic>> get store => intMapStoreFactory.store(storeName)
> ```
> 
> and
> 
> ```dart
> await store.add(db, map);
> ```
> 
> without changing your imports. However add/put is now available as an [extension](https://pub.dev/documentation/sembast/latest/sembast/SembastStoreRefExtension.html). Autocomplete is not fully working yet for extensions. This also means that your min sdk should be '>=2.6.0' in your pubspec.yaml. Can you check that? Otherwise can you report the error you are seeing? thanks!

Humm.. Got it. Worked here. Thanks, man.
