### ISSUE TITLE
how to check if the database type is already registered ?

### ISSUE THREAD

**Issue by Halim78** [tekartik/sembast.dart#214]

**Comment by alextekartik** [comment]
I'm guessing you are talking about custom types (such as Blob and Timestamp). Currently since you specify when you open the database the codec to use, you should know about the custom type registered. Support is minimal today. There is an example here https://github.com/tekartik/sembast_flutter_more.dart/tree/master/cloud_firestore_type_adapters where custom types (firestore ones) are supported.

Otherwise the list of supported types is fixed as defined here: https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/data_types.md

- `String`
- `num` (`int` and `double`)
- `Map<String, dynamic>`
- `List<dynamic>`
- `bool`
- `null`
- `Blob` (custom type)
- `Timestamp` (custom type)
