### ISSUE TITLE
[Question] Open database time ?

### ISSUE THREAD

**Issue by bounty1342** [tekartik/sembast.dart#241]
Hi,

Opening a database of 109KB, take around 2 sec.

```
Future<void> _openDatabase() async {
  final DateTime debut = DateTime.now();

  // get the application documents directory
  final Directory dir = Platform.isIOS
      ? await getApplicationSupportDirectory()
      : await getApplicationDocumentsDirectory();

  if (!await dir.exists()) {
    // make sure it exists
    await dir.create(recursive: true);
  }

  // build the database path
  final String dbPath = join(dir.path, 'db.db');

  // open the database
  await databaseFactoryIo.openDatabase(dbPath, version: 1);
  print(
      'fin _openDatabase openDatabase2 ${DateTime.now().difference(debut).inMilliseconds} ');
}
```

Is this expected or something else going on ?

**Comment by bounty1342** [comment]
```
[✓] Flutter (Channel unknown, 1.22.6, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/bounty1342/fvm/versions/1.22.6
    • Framework revision 9b2d32b605 (8 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/bounty1342/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • SM G780F (mobile) • RF8N93H62XP • android-arm64 • Android 11 (API 30)
```

**Comment by alextekartik** [comment]
The fact that sembast loads everything into memory indeed can lead to slow opening. If you follow the recommendations here, performance should be ok (https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/usage_recommendations.md). Big records (json decoding itself is slow for big data, whatever big means) slows thing a lot.

You could also try sembast_sqflite (it is just a different factory) which is cross process safe and has no compact drawbacks.

Unfortunately I don't have good benchmark. Personally on flutter I either load the database during the splash screen or after displaying a start screen so that it does not feel slow. And sometimes I use sqflite (mobile/desktop) or indexeddb for very big data.

**Comment by bounty1342** [comment]
Thanks for your feedback.

I'll try sembast_sqflite, but 2sec for 100 rows, this seems odd.

**Comment by psine** [comment]
I know this is closed, but in my testing of an entirely different database (Isar), I've seen getApplicationSupportDirectory() alone take a full second, before even opening the database, while actually opening the db takes around 200ms and loading many rows takes just a few milliseconds.  You might also try Stopwatch to isolate where your delay(s) are occurring.  It's a bit more convenient than DateTime.
