### ISSUE TITLE
Is get record by key is better or using filters

### ISSUE THREAD

**Issue by deep1931** [tekartik/sembast.dart#272]
I have thousands of records to save and retrieve, currently, I am saving data using record(key) and using the same to retrieve specif records. But if I want to save multiple records at once then store.addAll() is useful, but in this case when I need to retrieve or update any record then I need to use filters. 

The question is, which is more efficient and fast when we have thousands of records, and which is recomended. 

Please explain and help me to make an efficient process. 

Regards.

**Comment by alextekartik** [comment]
`record(key)` is the most efficient way to retrieve a record and is almost immediate compared to `Filter` by keys.
When you use store.addAll, you get a list of keys so it is still more efficient to use them.

To update thousands of record, you can either create a transaction and update each record individually in the transaction or you can use `store.records([key1, key2,...])` and update/add all them with a specific content for each.

I might not answer you question correctly. If you have a more specific scenario, I can help in finding the most efficient way.

**Comment by deep1931** [comment]
Thanks for the response. 

Let me share what I am trying to achieve

I have made a functionality similar to Whatsapp Sharing, I select multiple images from the gallery and then choose multiple contacts to send. At the time of sending, I have a list of contact, which I iterate through a loop to send messages to each contact. In this same function, I am calling to insert the same packet into the local DB (that is sembast) in the same loop.  

Before inserting the record, I get all records to count and increment it with 1 to make a index (because I need index of records in other functionlaity),. I am inserting and retrieving all data by key, rather than a filter. 
Now here are some questions, as the app will have thousand and maybe lakhs of records so I need to take care while development


1.  Is the above-mentioned process is ok to insert an item and index or is there any efficient way that can boost the performance.
2. While inserting in the loop it skips some records, not all records inserted into local DB, I am unable to understand is there any problem to insert using loop.

Thanks..

**Comment by alextekartik** [comment]
1. I'm not sure I understand correctly but If I do, make sure to compute the index and save it in the record in a transaction (otherwise there is always a risk of computing an index and having it no longer valid once you save the record)

2. Sorry here as well I'm not sure I understand what you mean by "insert using loop". But yes you can have a loop and insert thousands of records. If some records are skipped well there is a bug somewhere. So far I am not aware of such issue in sembast but I could be wrong. If you can, try to reproduce the issue in a unit test https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/how_to.md#unit-test so that I can investigate

3. It is much more efficient to insert/update multiple records in a transaction. But if "sending messages" takes some time it is ok to insert/update a record each time you send a message. And when you save a single record there is no need for a transaction (a transaction is automatically created for you).

Not sure I was really helpful...sorry...

**Comment by deep1931** [comment]
Thanks for the explanation, will try to reproduce the issue and share it with you.
