### ISSUE TITLE
[Question] Restart database after import it?

### ISSUE THREAD

**Issue by pckimlong** [tekartik/sembast.dart#289]
In my app, I use google drive to backup sembast database. After I use importDatabase function to restore the database back from google drive, It does not update my current database unless I restart the entire app. 

Is it possible to refresh the database without restarting the app?
Sorry for my English

**Comment by alextekartik** [comment]
You need to close the database (if opened) before importing at the same location and then opening it again. Otherwise the behavior is unknown since importDatabase creates a new database and your existing opened database still have the old content. Of course that means that at some point your current database will be closed which can be a pain to handle everywhere in your app.

An alternative (that I use personally) would be to import the database in a temp location, or even in memory and call databaseMerge  (in utils/database_utils.dart) to merge the temp database to your currently open database.

```dart
// Assuming exportMap is you export, the name 'export' could be anything
// Assuming db is your current opened database

// Import in a database in memory
var sourceDb = await importDatabase(exportMap, newDatabaseFactoryMemory(), 'export');
// Merge into opened database
await databaseMerge(db, sourceDatabase: sourceDb);
// Close the temp database
await sourceDb.close();
```

**Comment by pckimlong** [comment]
As you said closing the database and opening it again is such a pain when I almost use stream all around. I've followed your sample code by using databaseMerge and it worked as expected, Thank you for your response.
