### ISSUE TITLE
How to get last insert id?

### ISSUE THREAD

**Issue by kalismeras61** [tekartik/sembast.dart#29]
when insert new data I want to get last id same time. How can i do that?

**Comment by alextekartik** [comment]
If I understand correctly, you want to get the latest inserted id. You can only get the latest auto-generated inserted id when you add a record.
https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/writes.md#using-auto-generated-int-key

```dart
// Use the main store for storing map data with an auto-generated
// int key
var store = intMapStoreFactory.store();

// Add the data and get its new generated key
var key = await store.add(db, {'value': 'test'});
```

(More info about accessing data since it is a recent API here: <https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/new_api.md>)

**Comment by kalismeras61** [comment]
Ok thanks, i got id whit this, but i have another problem the problem is i have save users with firebase user id in my store i want to get record id with uid query. I am using below query but i did not get id. How can i do that?

  Future<Baby> getUserBabyId(String uid) async {
    var finder = Finder(
      filter: Filter.equal("uid", uid),
    );
    var babies = await _babyStore.findFirst(
      await _db,
      finder: finder,
    );

    var baby = Baby.fromMap(babies.value);
    print("id: ${baby.id}");
  return baby.id;
  }

**Comment by alextekartik** [comment]
You can directly get the key (i.e. the id) of the `RecordSnapshot` returned by `findFirst`. See <https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/queries.md#finding-first>

```dart
// Find the first record matching the finder
var record = await store.findFirst(db, finder: finder);
// Get the record id
var recordId = record.key;
// Get the record value
var recordValue = record.value;
```

**Comment by kalismeras61** [comment]
Thanks
