### ISSUE TITLE
ImmutableMap<String, dynamic>' is not a subtype of type 'Map<String, String>' in type cast

### ISSUE THREAD

**Issue by devxpy** [tekartik/sembast.dart#30]
Hey there! Thanks for this much needed library for dart!

I tried using the new Store API to find some records, by filtering based on keys, but it throws an error.

```dart
import 'package:sembast/sembast.dart';
import 'package:sembast/sembast_io.dart';

main() async {
  final db = await databaseFactoryIo.openDatabase("test.db");
  final store = StoreRef<String, Map<String, String>>.main();

  for (var i = 0; i < 10; i++) {
    await store.record(i.toString()).put(db, {"value": i.toString()});
  }

  await store.find(
    db,
    finder: Finder(
      filter: Filter.custom((record) {
        return record.key != "1";
      }),
    ),
  );
}
```

produces the following error:-
```
Unhandled exception:
type 'ImmutableMap<String, dynamic>' is not a subtype of type 'Map<String, String>' in type cast
#0      new SembastRecordSnapshot.fromRecord (package:sembast/src/record_snapshot_impl.dart:65:34)
#1      _SembastStoreRef&Object&StoreRefMixin.find.<anonymous closure> (package:sembast/src/store_ref_impl.dart:98:26)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#3      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#4      _SembastStoreRef&Object&StoreRefMixin.find (package:sembast/src/store_ref_impl.dart:99:11)
<asynchronous suspension>
#5      main (file:///home/dev/FlutterProjects/meghshala_app_flutter/test.dart:12:15)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

P.S. This works fine using the regular `db.findRecords()` API

**Comment by alextekartik** [comment]
Thanks for catching this. Indeed there are some limitations not clarified in the documentation and not checked earlier. The store API only supports declaring map of type `Map<String, dynamic>` as it is the way it is saved internally. Supporting `Map<String, String>` would required an extra cast that could impact performance on read.

Can you try using this instead?
```
final store = StoreRef<String, Map<String, dynamic>>.main();
```

I hope you can live with this limitation.
I will update sembast to throw a better exception earlier with a better explanation.

I have also updated the documentation here:
https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/new_api.md#supported-types

**Comment by purplecandy** [comment]
Why you have set the data returned from find or get to Immutable ? I mean it makes unnecessary cloning of objects when the only way to change data inside the database is though specific methods.

**Comment by alextekartik** [comment]
It was done mainly for performance since data was always cloned before even when it was only read. So now the raw stored data is returned letting the developer cloning only when/if needed. Cloning is only needed when you want to change the data.

That is said, I'm opened to suggestions. I have some LazyMutable map that I could use for the `RecordSnaphost.value` that would allow returning a map that the user can modify without affecting the stored value.

I'm trying to push on the new Store API where immutable is enforced. Can you tell which API (when you say get is it  `Database.get` or `RecordRef.get`?) you were pointing at? thanks

**Comment by purplecandy** [comment]
My use case is creating something like a watchlist: 
Where the type of structure of stored data is something like this 
`Map<String,dynamic> map = {
"id":1234,
"title":"Title",
"favourite": [items]
}`
```
final finder = Finder(filter: Filter.equal("id", Data.id));
      result = await storeob.find(trackdb, finder: finder);
```
I am using the find method to get the specific item. (Do tell me if there is a better way, honestly the API needs more documentation)

If the result has data, store it in a model class, parse the model class and display a list of items. 

After performing modification (which is not possible directly due to Immutable list). update the data in database.

What you mentioned is worth considering. Still it would nice to have optional parameter to disable/enable immutable object in exchange of performance.

**Comment by alextekartik** [comment]
Yes sorry about the documentation...not a lot of time for that. You can get a record by a key following this https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/new_api.md#after
```dart
var value = await store.record(key).get(db);
```
which is more efficient than a find.
I realize that your issue has nothing to do with the original question...we might switch to a new issue

**Comment by GMC254** [comment]
The reason this issue came up is because the documentation in the new release V. 1.15.0 mentions it. Please update that part of the documentation. See picture below.
![sembast documentation](https://user-images.githubusercontent.com/31553284/59165377-784ded80-8b23-11e9-9d59-0ec18146cb64.png)

**Comment by GMC254** [comment]
I think the main reason this came up was because of the documentation. The documentation in V. 1.15.0, may be the problem. See attached picture. Thanks for developing this life saving package.
![sembast documentation](https://user-images.githubusercontent.com/31553284/59165470-c3b4cb80-8b24-11e9-9dc2-6e6eb7541ae9.png)

**Comment by GMC254** [comment]
I think the main reason this issue came up was because of the documentation. The documentation in V. 1.15.0, may be the problem. See attached picture. Please update the documentation. 
![sembast documentation](https://user-images.githubusercontent.com/31553284/59165493-13939280-8b25-11e9-9108-b9ed2f249e9d.png)
Thanks for developing this life saving package.

**Comment by alextekartik** [comment]
Well actually the documentation is correct here (although I never use it this way) and the code works: https://github.com/tekartik/sembast.dart/blob/52bbaa4caec1aeec15edb2a59a44672f57b07534/sembast/test/doc_test.dart#L58-L72

It indicates here that the key is a String and the values are Strings. 

The initial issue here was about a `StoreRef<String, Map<String, String>>` declaration (i.e. keys are Strings and values are Map<String, String> which is not supported as Map have to be of type Map<String, dynamic>). I personnally recommend using `intMapStoreFactory` or `stringMapStoreFactory` for defining a store.

**Comment by GMC254** [comment]
Thanks. I misread the issue.

**Comment by AndryHTC** [comment]
I have a similar problem with stringMapStoreFactory. If I create the map I can manage it and change his key/values... If I get the same map from the Sembast record, and I try to change his key/values I get:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Bad state: read only
E/flutter ( 7909): #0      ImmutableMap.[]= (package:sembast/src/utils.dart:218:40)
```
I've tried a couple of different stores to avoid this:
- StoreRef<String, dynamic>
- StoreRef<String, Map>
- StoreRef<String, Map<String, dynamic>>
- stringMapStoreFactory (like suggested by you)

What's wrong in my use case? Are there solution? Or is it a bug?

**Comment by alextekartik** [comment]
The map is immutable. You need to create a new map. The simplest way is to clone the map using [`cloneMap`](https://pub.dev/documentation/sembast/latest/utils_value_utils/cloneMap.html)

**Comment by AndryHTC** [comment]
Really? Less than 20 min to reply... You're truly active @alextekartik 
It's a pleasure to have this type of developers around the world 👍
