### ISSUE TITLE
Specify the length of the auto-generated string id

### ISSUE THREAD

**Issue by theoriginaltudor** [tekartik/sembast.dart#92]
First I want to say tank you for sembast. It is helping me a lot.
Now my problem is that I have an online MongoDB and I'm using sembast for my offline DB. And when I create a record in sembast(the application is offline) I get an auto-generated string id of 20 characters. If I try to use that id when I get back online and synchronize the data (i'm just sending the new data to the MongoDB to be created), I get an error from MongoDB that the id should either be 16 or 24. Do you know a way to change the length of the auto-generated string id?

**Comment by alextekartik** [comment]
Thanks for the note. The ID generation used the one used by firebase as specified here https://firebase.googleblog.com/2015/02/the-2120-ways-to-ensure-unique_68.html

I'm not sure what I would do to accomodate to 16 chars nor 24 (besides padding).

Typically in this scenario, I would not try to match sembast and mongo ids but would rather let mongo generate one when syncing and saving this generated mongo id in sembast (in a local sync_id field). And you could even keep the id as an int on the sembast side.

Otherwise, maybe you could simply pad the generated id to match 24 characters...
