### ISSUE TITLE
To close or not to close...

### ISSUE THREAD

**Issue by ejain** [tekartik/sembast.dart#96]
None of the sample code appears to bother calling `Database.close()`, so can we assume that calling this method is not necessary in order to avoid lost writes?

**Comment by alextekartik** [comment]
That's a good question. In most apps since you don't control when your application quits, there is not way to properly cleanup things. The system will do it. Actually the file itself is only open the first time for reading and after each write to append data. In the worst case, the last data inserted could be corrupted, sembast will simply ignore corrupted records. There is no flush method, data is written lazily immediately after writing to the database.

**Comment by ejain** [comment]
Thanks for clarifying. I did find one use for `close()`: Looks like this method needs to be called prior to calling `deleteDatabase()`, if you want the database file to be removed (at least on Windows)...
